#!/bin/sh

###############################################################################
#                                                                             #
#                                   echolor                                   #
#                                                                             #
#  Description:                                                               #
#    Color a message according to informed color.                             #
#                                                                             #
#  How to use:                                                                #
#    echolor [-n] "String" COLOR                                              #
#                                                                             #
#  Example:                                                                   #
#    echolor "Light green text" LIGHTGREEN                                    #
#                                                                             #
#  Options:                                                                   #
#    COLOR                                                                    #
#      One of the following colors: BLACK, BLUE, CYAN, DARKGRAY, GREEN,       #
#      LIGHTBLUE, LIGHTCYAN, LIGHTGRAY, LIGHTGREEN, LIGHTPURPLE, LIGHTRED,    #
#      ORANGE, PURPLE, RED, WHITE or YELLOW. If another value is informed,    #
#      the string will not be colored.                                        #
#                                                                             #
#    -n                                                                       #
#      Do not output the trailing newline.                                    #
#                                                                             #
#  WWW:                                                                       #
#    github.com/lbezerril/sh-utils/blob/master/echolor                        #
#    * This script is part of a utilities project in POSIX Shell              #
#      (github.com/lbezerril/sh-utils)                                        #
#                                                                             #
#  Documentation:                                                             #
#    github.com/lbezerril/sh-utils/tree/master/echolor                        #
#                                                                             #
#  Author:                                                                    #
#    lbezerril (github.com/lbezerril)                                         #
#                                                                             #
#  License:                                                                   #
#    GNU GPL v3 (github.com/lbezerril/sh-utils/blob/master/LICENSE)           #
#                                                                             #
#  This POSIX sh is following the "posix-guidelines" version="1.0.0" {        #
#    <https://github.com/lbezerril/posix-guidelines/tree/1.0.0>               #
#  }                                                                          #
#                                                                             #
#                                                                             #
###############################################################################

if [ -z "$2" ]; then
  echo "Use: echolor [-n] \"String\" COLOR"
  exit 1
fi

# If there is the third argument, and the first one is "-n", assign to a
# variable the option to be used in the echo command.
if [ ! -z "$3" ] && [ "$1" = "-n" ]; then
  option="-n"
  shift
fi

NC='\033[0m'

# Assigns the color code informed.
case "$2" in
  "BLACK")
    color_code='\033[0;30m';;
  "BLUE")
    color_code='\033[0;34m';;
  "CYAN")
    color_code='\033[0;36m';;
  "DARKGRAY")
    color_code='\033[1;30m';;
  "GREEN")
    color_code='\033[0;32m';;
  "LIGHTBLUE")
    color_code='\033[1;34m';;
  "LIGHTCYAN")
    color_code='\033[1;36m';;
  "LIGHTGRAY")
    color_code='\033[0;37m';;
  "LIGHTGREEN")
    color_code='\033[1;32m';;
  "LIGHTPURPLE")
    color_code='\033[1;35m';;
  "LIGHTRED")
    color_code='\033[1;31m';;
  "ORANGE")
    color_code='\033[0;33m';;
  "PURPLE")
    color_code='\033[0;35m';;
  "RED")
    color_code='\033[0;31m';;
  "WHITE")
    color_code='\033[1;37m';;
  "YELLOW")
    color_code='\033[1;33m';;
  *)
    color_code=$NC;;
esac

echo ${option} "${color_code}${1}${NC}"
